name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.release.tag_name }}
          tag_name: ${{ github.event.release.tag_name }}
